server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5450/postgres
    username: product_service
    password: product_service
    hikari:
      schema: products

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:29095,localhost:29096,localhost:29097
    admin:
      auto-create: true
    topic:
      notification: electronics.store.notification.request

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/electronics-store

springdoc:
  api-docs:
    path: /product-service/v3/api-docs
  swagger-ui:
    path: /product-service/swagger-ui.html

logging:
  level:
    org:
      zalando:
        logbook:
          Logbook: TRACE

custom:
  feign:
    client:
      user:
        service:
          url: http://localhost:8082/api/v1/users